[package]
name = "rust_matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
colorsys = "0.7.1"
crossterm = { version = "0.29.0", default-features = false, features = ["events"] }
ctrlc = { version = "3.5.0", features = ["termination"] }
rand = { version = "0.9.2", features = ["small_rng"] }
